### PR TITLE
Analytics: fix build with libcurl/7.50.0 and higher (typedef conflict)

### PR DESCRIPTION
**Pull request by GhettoGirl**
curl 7.50 defines CURL (**typedef**) in its header which conflicts with the typedef from ```Analytics.h``` and causes compilation to fail with the latest curl version.

I added a preprocessor check for *LIBCURL_VERSION_NUM* to workaround this issue and fix the build for people with the latest curl release.

--

```
In file included from /build/emulators/dolphin/Source/Core/Common/Analytics.cpp:10:0:
/build/emulators/dolphin/Source/Core/Common/Analytics.h:19:14: error: conflicting declaration ‘typedef void CURL’
 typedef void CURL;
              ^~~~
In file included from /build/emulators/dolphin/Source/Core/Common/Analytics.cpp:7:0:
/usr/include/curl/curl.h:94:26: note: previous declaration as ‘typedef struct Curl_easy CURL’
 typedef struct Curl_easy CURL;
                          ^~~~
```

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4062)

### CODE REVIEW

**Comment by leoetlino** [comment]
@dolphin-emu-bot rebuild

**Comment by GhettoGirl** [comment]
fixed in #4066
