### PR TITLE
Fix build with Qt 5.15+

### PR DESCRIPTION
**Pull request by sl1pkn07**
Fix build with Qt 5.15

~~~
 95%] Building CXX object Source/Core/DolphinQt/CMakeFiles/dolphin-emu.dir/NetPlay/GameListDialog.cpp.o
/tmp/makepkg/sl1-dolphin-emu-git/src/dolphin-emu/Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp: En la función miembro ‘virtual void SwingIndicator::DrawUnderGate(QPainter&)’:
/tmp/makepkg/sl1-dolphin-emu-git/src/dolphin-emu/Source/Core/DolphinQt/Config/Mapping/MappingIndicator.cpp:485:18: error: el agregado ‘QPainterPath path’ tiene un tipo incompleto y no se puede definir
  485 |     QPainterPath path;
      |                  ^~~~
~~~

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild
