### PR TITLE
JitArm64: Fix false positive "turned singles into doubles" asserts

### PR DESCRIPTION
**Pull request by JosJuice**
Fixes a regression from PR #9472.

### CODE REVIEW

File: Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp [hunk 1]
```diff
@@ -219,7 +221,7 @@ void JitArm64::fselx(UGeckoInstruction inst)
   const u32 d = inst.FD;
 
   const bool a_single = fpr.IsSingle(a, true);
-  if (fpr.IsSingle(a, true))
+  if (a_single)
```
Comment (JosJuice) [inline Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp:224]: This is not a functional change, but all the other changes are.

**Review by leoetlino — APPROVED** [review]
